### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by anandology** [pipalacademy/riyaz#1]
Create a simple homepage listing all courses.

## Mockup

![image](https://user-images.githubusercontent.com/7569/184313838-7ac0fd01-4906-459e-9530-b4633ca111e3.png)

**Comment by nikochiko** [comment]
Added to look like this
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/37668193/184647481-f1c3354e-9101-4897-8941-c8e3c021e652.png">

Edit:
https://github.com/pipalacademy/riyaz/commit/aefcc089c16d46cb1bfd61b134dfe3bcc5ab0cba should be linked to this issue instead.

**Comment by anandology** [comment]
Looks good. One small is that the navbar in fluid layout and the body is in the fixed layout. 

Can you keep nav contents in a `container` instead of a `container-fluid`?

**Comment by nikochiko** [comment]
done.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/37668193/184792566-ad726954-9e8c-47dc-9191-fa3a64968792.png">

**Comment by anandology** [comment]
done.
