### ISSUE TITLE
move to simple SQL 

### ISSUE THREAD

**Issue by anandology** [pipalacademy/riyaz#17]
We are using a document database created on top of sqlite. It feels a bit limiting and unnecessary abstration. It may be a lot simpler and effective in the long run to use SQL and simple abstractions.

## Approach

I propose using [web.py database][1] for this. web.py makes it easier to write SQL without adding complex abstractions. 

[1]: https://webpy.readthedocs.io/en/latest/db.html

For migrations, we can have a simple `migrate.py` with all the migration steps.

The `Document` class in the `db` module will be replaced by a `BaseModel` that will continue to support the `find`, `find_all` and `save` methods.

**Comment by nikochiko** [comment]
That would be a simple enough interface. LGTM 👍

**Comment by anandology** [comment]
done.
