### ISSUE TITLE
Discussion: `riyaz serve` command

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/riyaz#18]
`riyaz serve` command is already merged in the codebase.

It works like this:
1. Create a `riyaz.db` in the current directory (if it doesnt exist)
2. Run `schema.sql` migrations on it (if table `document` doesn't exist)
3. Load sample data from `sample_data/` directory (using code in sample_data.py)
4. Read course from current directory, push it to database
5. Start a Flask server

**More features that we want:**
* [x] #19

**Comment by nikochiko** [comment]
Some ad-hoc decisions were made here:
* Creating `riyaz.db` file in the current directory. Would it be desirable to have:
    * `riyaz.db` in a temporary directory, that will be destroyed when `riyaz serve` is killed
    * `riyaz.db` in the same place (like in [`$XDG_DATA_HOME`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables), `~/.local/share/`)
* Loading sample data as a demo for the user
* Not having a feature for allowing user to mention a directory as an argument (current directory is assumed)

**Comment by anandology** [comment]
> Some ad-hoc decisions were made here:
> 
>     * Creating `riyaz.db` file in the current directory. Would it be desirable to have:
>       
>       * `riyaz.db` in a temporary directory, that will be destroyed when `riyaz serve` is killed
>       * `riyaz.db` in the same place (like in [`$XDG_DATA_HOME`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables), `~/.local/share/`)
> 
>     * Loading sample data as a demo for the user
> 
>     * Not having a feature for allowing user to mention a directory as an argument (current directory is assumed)

What is the purpose of `riyaz serve`? If the purpose is to serve what is the current directory, then it should not load the sample data. If the purpose is to start a server, then it should not delete the database. 

Can you look at what `mkdocs serve` does and see how much of that is relevant to riyaz?

**Comment by nikochiko** [comment]
> Can you look at what mkdocs serve does and see how much of that is relevant to riyaz?

`mkdocs serve` builds to a temporary directory and runs a simple File Server from there. The directory is then deleted once the server is killed.

`watchdog` listens for fs events, and a `build` is triggered everytime a new event is received (there are waiting methods implemented).

**Comment by nikochiko** [comment]
> What is the purpose of riyaz serve? If the purpose is to serve what is the current directory, then it should not load the sample data. If the purpose is to start a server, then it should not delete the database.

I think both could be reasonable ways of doing it.
One is relevant only to course authors, other is relevant to developers who want to host more than one course.

It makes sense not to load user data, especially now because user has the `riyaz new` command that will give a template.

**Comment by anandology** [comment]
> `mkdocs serve` builds to a temporary directory and runs a simple File Server from there. The directory is then deleted once the server is killed.
> 
> `watchdog` listens for fs events, and a `build` is triggered everytime a new event is received (there are waiting methods implemented).

That sounds like a good approch to follow, doesn't it? You can create a temp directory and create riyaz.db in it and start serving.

**Comment by nikochiko** [comment]
Yes, it does.
I prefer that too.
