### ISSUE TITLE
Course page

### ISSUE THREAD

**Issue by anandology** [pipalacademy/riyaz#2]
The course page will have a header and three sections: about the course, course outline and instructor.

## Mockup

![image](https://user-images.githubusercontent.com/7569/184317123-d948f5d0-f9a3-4f8b-a959-8644ce57ae62.png)

**Comment by nikochiko** [comment]
This is done.
Demo is available at: http://riyaz.kaustubh-dev.pipal.in/courses/alpha-course

**Comment by anandology** [comment]
done.
