### ISSUE TITLE
New command: `riyaz new`

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/riyaz#21]
It should:
* help the course developer to understand where each file goes, and how the settings need to be specified
* give user a project template to fill in the blanks or swap out pieces

**Approach:**
* Add a `template/` folder in `sample-data/` that has files for chapters, lessons, authors, and course.yml
* When user runs `riyaz new {course-dir}`:
    1. Create directory `{course-dir}`, copy contents of `template/` into `{course-dir}/`. If directory exists, an error should be raised.
    2. Load `{course-dir}/course.yml` into memory, change value of `course: {course-dir}` to the title-fied version of `{course-dir}`.

The sample data loaded should have some demonstration of how to use the features provided by riyaz.

**Comment by anandology** [comment]
Wouldn't it be better to use [cookie-cutter][1] for this? 

[1]: https://github.com/cookiecutter/cookiecutter

You can look at an example at: 
https://github.com/pipalacademy/python-practice-problems/tree/main/cookiecutter-problem

**Comment by anandology** [comment]
> It should:
> 
>     * help the course developer to understand where each file goes, and how the settings need to be specified
> 
>     * give user a project template to fill in the blanks or swap out pieces

Shouldn't the goal just be:
- create a new empty course with all required files from a predefined template

**Comment by nikochiko** [comment]
Cookie cutter makes sense.

> Shouldn't the goal just be:
>
> create a new empty course with all required files from a predefined template

Yeah, okay 👍 . We don't need to make the template content serve as documentation.

**Comment by nikochiko** [comment]
Should we have `cookiecutter` as a dependency and run it from python when `riyaz new` is run, or let the user run `cookiecutter` on their own?
