### ISSUE TITLE
Design plugin system for riyaz

### ISSUE THREAD

**Issue by anandology** [pipalacademy/riyaz#23]
Design a plugin system for riyaz to support extensions. The following are examples of some of the features that we would like a plugin to be able to do:

- add support for live code execution 
- add support for creating and presenting quizs
- support for projects
- discussions

This means, a plugin should be able to add:
- css and javascript to be included globally
- css and javascript to be included on select pages
- add a markdown extension
- add custom routes

Please feel free to suggest any other things that a plugin should be able to do.

**Comment by anandology** [comment]
A plugin system seems a bit more complicated than what I initially thought. To understand how the plugin system may possibly be implemented, I would like to take the document how plugins of mkdocs, infogami and Frappe implement plugins and what suits for Riyaz from those ideas.

## mkdocs

[Mkdocs plugins][0] are written as a [plugin class][1] with a method for [every possible event][2]. 

```
class MyPlugin:
    def on_config(self, config, **kwargs):
        pass

    def on_files(self, files, config):
        pass
```

The plugin class name is specified in the [setup.py entrypoints][3].

```
entry_points={
    'mkdocs.plugins': [
        'pluginname = path.to.some_plugin:SomePluginClass',
    ]
}
```

### Notes

While this approach takes care of all possible case, the plugin development is very tightly coupled with how mkdocs works. For example, if I want to include or exclude some files, you need to understand how file loading of mkdocs works, find the appropriate event method to implement.

While this approach seems good and comprehensive, I find the a bit difficult to get started.

[0]: https://www.mkdocs.org/dev-guide/plugins/
[1]: https://www.mkdocs.org/dev-guide/plugins/#baseplugin
[2]: https://www.mkdocs.org/dev-guide/plugins/#events
[3]: https://www.mkdocs.org/dev-guide/plugins/#entry-point

## Infogami

[Infogami][in0] uses a very simple plugin system. Every plugin is expected to have a `code.py` and the code.py will have to code to register new routes, new wiki macros etc. The code.py can have a function `setup` which will be called after the plugin is imported. It also supports hooks for taking actions on various events.

For example, the `wikitemplates` plugin of Infogami provides support for writing templates and macros right in the webapp as a special page. Here are some code snippets of how it is implemented:

* [The setup method][in3]
* [Adding new source of templates and macros][in1]
* [Hooks to perform some action before and after a new version of a page is created][in2]

[in0]: https://github.com/internetarchive/infogami
[in1]: https://github.com/internetarchive/infogami/blob/master/infogami/plugins/wikitemplates/code.py#L104-L110
[in2]: https://github.com/internetarchive/infogami/blob/master/infogami/plugins/wikitemplates/code.py#L113-L131
[in3]: https://github.com/internetarchive/infogami/blob/master/infogami/plugins/wikitemplates/code.py#L192

### Notes

While the plugin system of infogami is not very sophisticated, it clearly seperate out two different ways to customize. 

1. registering new routes, template sources etc.
2. hooks for various events

This seperation makes it easier to write a new plugin. For example, if someone wants to write a new plugin that adds a `/hello-world` page, it just need to add a new route and not worry anything about various events of Infogami.

## Frappe

Plugins are called apps in Frappe and each app can contain multiple modules.

Frappe has a two ways to extend it.
1. conventions
2. hooks

Frappe allows you to specify files in a specific path like doctypes and portal pages and they just get loaded and no configuration is required. This makes it very easy for writing simple plugins. 

In addition to this, frappe also supports _hooks_. There will be a [hooks.py][f1] in every app and it can specify any of the [available hooks][f2].

Hooks are simple and interesting, but also have their own quirks.

> Now, the hook value can be consumed in different ways. For example, for including JS assets using `app_include_js`, all of the values are included. But for overriding whitelisted method, the last value in the list is used.
> 
> So the implementation of the hook is totally dependent on how the author of the feature intended it to be used.

Also: 

> When you call frappe.get_hooks, it will convert all the values in a list. This means that if the hook is defined in multiple apps, the values will be collected from those apps. This is what enables the cascading nature of hooks.

This is gets tricky.

[f1]: https://frappeframework.com/docs/v13/user/en/python-api/hooks
[f2]: https://frappeframework.com/docs/v13/user/en/python-api/hooks#list-of-available-hooks

### Notes

The hooks.py is simple and declarative, but it gets a bit tricky because these gets converted to a list.

Since Frappe stores all the collected hooks in redis for faster access, all the values specified there must be serializable. For example, you can't even add an import to this module because module is not JSON-serializable.

Also, Frappe doesn't import the plugins on load and it is not clear when would a module be imported, making it hard to register custom routes etc.

**Comment by anandology** [comment]
To avoid delay in implementing other features, here is a proposal for a simple plugin system for the time being.

Have the following functions in app.py.

```
def include_javascript(url):
    """Adds the given url to the list of javascripts included in every page"""
    pass

def include_stylesheet(url):
    """Adds the given url to the list of stylesheets included in every page"""
    pass
```

A plugin could be just a module and it would call these functions to include any custom styles and scripts required for it to work.

The other issue is how do we specify what plugins to load and how are they loaded.

For now, we can import these at the end of app.py. That is not a nice thing as it would create a circular dependency, but we can worry about it later.

@nikochiko what do you think?

**Comment by nikochiko** [comment]
Yeah, this is good enough for now.

I think when we allow more people to design and use plugins, we can do some engineering and load the plugins better with more flexibility.

**Comment by nikochiko** [comment]
Here is my approach in doing this:

1. Initialize two lists in `app.py` as module variables. (`stylesheet_urls`, `javascript_urls`)
2. `add_javascript` will append to `javascript_urls`, `add_stylesheet`will append to `stylesheet_urls`
3. Add an [`app.context_processor`](https://flask.palletsprojects.com/en/2.2.x/templating/#context-processors)  that will inject these two variables into the jinja context.
4. In `templates/base.html`, loop over `stylesheet_urls` and `javascript_urls` to add them in the right places

This is the simplest I could think of, without new classes or any more engineering involved.
