### ISSUE TITLE
Lesson Page

### ISSUE THREAD

**Issue by anandology** [pipalacademy/riyaz#3]
The lesson page will have show the lesson title followed by the lesson contents. It will also have breadcrumbs in the top to go back the course.

## Mockup

![image](https://user-images.githubusercontent.com/7569/184319224-36f3f112-7885-4149-b9a4-7567881bc944.png)

**Comment by nikochiko** [comment]
For lesson page, we have some candidates for the URL:
1. `/courses/:course_name/:module_name/:lesson_name`
2. `/courses/:course_name/lessons/:module_name/:lesson_name`
3. `/lessons/:course_name/:module_name/:lesson_name`

I think option 1 makes sense.

**Comment by nikochiko** [comment]
This is how it looks right now
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/37668193/184877283-c6224a23-bb85-4414-bacc-069717a80076.png">

**Comment by anandology** [comment]
done.
