### ISSUE TITLE
Implement simple db module

### ISSUE THREAD

**Issue by anandology** [pipalacademy/riyaz#6]
Implement a db module with a simple interface.

## API

```
db.get(doctype, key) -> Document
db.get_many(doctype, keys) -> List[Document]
db.query(doctype, field1='a', field2='b') -> List[Document]
```

It also supports defining classes for each doctype.

```
@db.register_model("course")
class Course(db.Document):
    def get_authors(self):
        ...
```

## Tasks

...

**Comment by anandology** [comment]
Implemented the db, the support for models is not done.

**Comment by nikochiko** [comment]
For each thing, can the key change or is it constant like ID?

While making references from inside JSON, should we use the key or the ID of the other thing?

**Comment by anandology** [comment]
done. But, we may replace this with simple sql.
